# Generated by Django 6.0.2 on 2026-03-01 06:16

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_codedcommand_to_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='access_token',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='refresh_token',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='owner_access_token',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='owner_refresh_token',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
