# Generated by Django 6.0.2 on 2026-03-08 03:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_convert_skills_to_commands'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50)),
                ('twitch_id', models.CharField(max_length=50)),
                ('twitch_username', models.CharField(blank=True, default='', max_length=100)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_stats', to='core.channel')),
            ],
            options={
                'ordering': ['skill_name', 'twitch_username'],
                'unique_together': {('channel', 'skill_name', 'twitch_id')},
            },
        ),
    ]
