# Generated by Django 6.0.5 on 2026-06-26 19:09

import core.models
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_twitch_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=core.models._generate_invite_code, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('channel_twitch_id', models.CharField(blank=True, default='', max_length=50)),
                ('channel_name', models.CharField(blank=True, default='', max_length=100)),
                ('channel_access_token', encrypted_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('channel_refresh_token', encrypted_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('channel_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
