# Generated by Django 6.0.5 on 2026-07-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_approve_existing_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='bot_oauth_nonce',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
