# Generated by Django 6.0.5 on 2026-07-01 23:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_invite_bot_oauth_nonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='LizardPlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitch_id', models.CharField(db_index=True, max_length=50)),
                ('twitch_username', models.CharField(blank=True, default='', max_length=100)),
                ('outcome', models.CharField(max_length=20)),
                ('was_bullet', models.BooleanField(default=False)),
                ('is_scripted', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=True)),
                ('mood', models.CharField(max_length=20)),
                ('mood_weights', models.JSONField(blank=True, default=dict)),
                ('deaths', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lizard_plays', to='core.channel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'twitch_id', 'created_at'], name='core_lizard_channel_a2aacd_idx')],
            },
        ),
    ]
