# Generated by Django 6.0.5 on 2026-07-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_lizard_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='lizardplay',
            name='offline_tier',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
