# Generated by Django 6.0.7 on 2026-07-20 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_lizard_play_offline_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonWager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_key', models.CharField(db_index=True, max_length=32)),
                ('twitch_id', models.CharField(max_length=50)),
                ('twitch_username', models.CharField(blank=True, default='', max_length=100)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('wager', models.PositiveIntegerField()),
                ('payout', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_wagers', to='core.channel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'status'], name='core_dungeo_channel_dd7aa9_idx')],
            },
        ),
    ]
