# Generated by Django 6.0.7 on 2026-07-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_dungeon_wager'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillstat',
            name='bullet_deaths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillstat',
            name='deaths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillstat',
            name='last_mood',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='skillstat',
            name='max_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillstat',
            name='plays',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillstat',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillstat',
            name='streaks_broken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillstat',
            name='survivals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
