# Generated by Django 6.0.7 on 2026-07-21 02:19

from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_freeze_tenant_skill_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lizardplay',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
