# Generated by Django 6.0.7 on 2026-07-28 19:04

import uuid

from django.db import migrations, models


def randomize_overlay_keys(apps, schema_editor):
    """AddField evaluates the callable default once, giving every existing
    row the same key — re-randomize so channels never share one."""
    Channel = apps.get_model("core", "Channel")
    for channel in Channel.objects.all():
        channel.overlay_key = uuid.uuid4()
        channel.save(update_fields=["overlay_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_prune_legacy_lizard_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='overlay_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(randomize_overlay_keys, migrations.RunPython.noop),
    ]
