# Generated by Django 6.0.7 on 2026-08-22 20:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_channel_overlay_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('interval_seconds', models.PositiveIntegerField(default=1800, help_text='Minimum seconds between sends.')),
                ('min_chat_lines', models.PositiveIntegerField(default=5, help_text='Chat messages required since the last send. 0 disables the gate.')),
                ('enabled', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_messages', to='core.channel')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('channel', 'name')},
            },
        ),
    ]
