# Generated by Django 6.1 on 2026-09-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_timedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
