/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitesRouteImport } from './routes/invites'
import { Route as ChannelSlugAliasesRouteImport } from './routes/$channelSlug/aliases'
import { Route as ChannelSlugCommandsRouteImport } from './routes/$channelSlug/commands'
import { Route as ChannelSlugCountersRouteImport } from './routes/$channelSlug/counters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesRoute = InvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelSlugAliasesRoute = ChannelSlugAliasesRouteImport.update({
  id: '/$channelSlug/aliases',
  path: '/$channelSlug/aliases',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelSlugCommandsRoute = ChannelSlugCommandsRouteImport.update({
  id: '/$channelSlug/commands',
  path: '/$channelSlug/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelSlugCountersRoute = ChannelSlugCountersRouteImport.update({
  id: '/$channelSlug/counters',
  path: '/$channelSlug/counters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invites': typeof InvitesRoute
  '/$channelSlug/aliases': typeof ChannelSlugAliasesRoute
  '/$channelSlug/commands': typeof ChannelSlugCommandsRoute
  '/$channelSlug/counters': typeof ChannelSlugCountersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invites': typeof InvitesRoute
  '/$channelSlug/aliases': typeof ChannelSlugAliasesRoute
  '/$channelSlug/commands': typeof ChannelSlugCommandsRoute
  '/$channelSlug/counters': typeof ChannelSlugCountersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invites': typeof InvitesRoute
  '/$channelSlug/aliases': typeof ChannelSlugAliasesRoute
  '/$channelSlug/commands': typeof ChannelSlugCommandsRoute
  '/$channelSlug/counters': typeof ChannelSlugCountersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invites'
    | '/$channelSlug/aliases'
    | '/$channelSlug/commands'
    | '/$channelSlug/counters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invites'
    | '/$channelSlug/aliases'
    | '/$channelSlug/commands'
    | '/$channelSlug/counters'
  id:
    | '__root__'
    | '/'
    | '/invites'
    | '/$channelSlug/aliases'
    | '/$channelSlug/commands'
    | '/$channelSlug/counters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitesRoute: typeof InvitesRoute
  ChannelSlugAliasesRoute: typeof ChannelSlugAliasesRoute
  ChannelSlugCommandsRoute: typeof ChannelSlugCommandsRoute
  ChannelSlugCountersRoute: typeof ChannelSlugCountersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites': {
      id: '/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof InvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$channelSlug/aliases': {
      id: '/$channelSlug/aliases'
      path: '/$channelSlug/aliases'
      fullPath: '/$channelSlug/aliases'
      preLoaderRoute: typeof ChannelSlugAliasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$channelSlug/commands': {
      id: '/$channelSlug/commands'
      path: '/$channelSlug/commands'
      fullPath: '/$channelSlug/commands'
      preLoaderRoute: typeof ChannelSlugCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$channelSlug/counters': {
      id: '/$channelSlug/counters'
      path: '/$channelSlug/counters'
      fullPath: '/$channelSlug/counters'
      preLoaderRoute: typeof ChannelSlugCountersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitesRoute: InvitesRoute,
  ChannelSlugAliasesRoute: ChannelSlugAliasesRoute,
  ChannelSlugCommandsRoute: ChannelSlugCommandsRoute,
  ChannelSlugCountersRoute: ChannelSlugCountersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
